server:
   port: 9191
   
spring:
   application:
      name: API-GATEWAY
   cloud:
      gateway:
         routes:
            - id: USER-APP
              uri: lb://USER-APP
              predicates:
               - Path=/user/**
              filters:
               - name: CircuitBreaker
                 args:
                  name: USER-APP
                  fallbackuri: forward:/userServiceFallback
            - id: SUBSCRIPTION-APP
              uri: lb://SUBSCRIPTION-APP
              predicates:
               - Path=/subscription/**
              filters:
               - name: CircuitBreaker
                 args:
                  name: SUBSCRIPTION-APP
                  fallbackuri: forward:/subscriptionServiceFallback

hystrix:
   command:
      fallbackcmd:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 4000
                  
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
      instance:
         hostname: localhost