server:
   port: 9091
   
spring:
   application:
      name: USER-APP
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: update
   h2:
      console:
         enabled: true
      path: /h2
   datasource:
      url: jdbc:h2:file:/Users/dthompson/Documents/repo/microservices/db/user/data;DATABASE_TO_UPPER=false
      username: sa
      password:
      driverClassName: org.h2.Driver

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
      instance:
         hostname: localhost